meta_product_name: "In Real Life"
meta_title: "Where friends help match you"
meta_description: "IRL facilitates matchmaking by leveraging your friends, ensuring genuine interactions and removing the hassle in introductions.  You can nominate match-makers and enable them to alert you when they find a potential suitable match for you, while always leaving you in total control.
  RealLife.love is free and will stay free if you sign-up now.
  We all have amazing single friends and it is a huge gift to be able to introduce future couples to each other.  RealLife.love makes this easy, notifying your friend on RealLife.love about potential matches from your network while keeping your RealLife.love friend in full control with making the introduction happen.  RealLife.love is free for now to join today!"
meta_image: "app/assets/images/HomeHero.jpg" # should exist in `app/assets/images/`
twitter_account: "@PaulPaulFor"   # required for Twitter Cards
