meta_product_name: "In Real Life"
meta_title: "RealLife❤ - Where friends help match you"
meta_description: "IRL facilitates meeting new people by leveraging your network of friends, ensuring genuine interactions and removing the hassle in introductions.
  We all have amazing single friends and it is a huge gift to be able to introduce future couples to each other.  IRL makes this easy!"
meta_image: "undraw_love_xfcv_nobkg.png" # should exist in `app/assets/images/`
twitter_account: "@contatc2"   # required for Twitter Cards # required for Twitter Cards
